phpCAS: docs/examples/example_gateway.php File Reference
docs/examples/example_gateway.php File Reference
Variables
$auth = phpCAS::checkAuthentication()
Variable Documentation
$auth = phpCAS::checkAuthentication()
Examples:
example_gateway.php.
Definition at line 26 of file example_gateway.php.
Referenced by phpCAS::checkAuthentication(), phpCAS::forceAuthentication(), and CASClient::wasPreviouslyAuthenticated().