phpCAS: CAS proxied client features (CAS 2.0, Proxy Tickets)
CAS proxied client features (CAS 2.0, Proxy Tickets)
[Implementation]
Functions
CASClient::getPT ()
CASClient::setPT ($pt)
CASClient::hasPT ()
CASClient::validatePT (&$validate_url, &$text_response, &$tree_response)
Variables
CASClient::$_pt
Function Documentation
CASClient::getPT () [private, inherited]
This method returns the Proxy Ticket provided in the URL of the request.
Returns:
The proxy ticket.
Definition at line 2031 of file client.php.
Referenced by CASClient::isAuthenticated().
CASClient::hasPT () [private, inherited]
This method tells if a Proxy Ticket was stored.
Returns:
TRUE if a Proxy Ticket has been stored.
Definition at line 2050 of file client.php.
CASClient::setPT ($ pt) [private, inherited]
This method stores the Proxy Ticket.
Parameters:
$pt The Proxy Ticket.
Definition at line 2042 of file client.php.
Referenced by CASClient::wasPreviouslyAuthenticated().
CASClient::validatePT (&$ validate_url, &$ text_response, &$ tree_response) [private, inherited]
This method is used to validate a PT; halt on failure
Returns:
bool TRUE when successfull, halt otherwise by calling CASClient::authError().
Definition at line 2069 of file client.php.
References phpCAS::trace(), and phpCAS::traceBegin().
Referenced by CASClient::isAuthenticated().
Variable Documentation
CASClient::$_pt [private, inherited]
the Proxy Ticket provided in the URL of the request if present (empty otherwise). Written by CASClient::CASClient(), read by CASClient::getPT() and CASClient::hasPGT().
Definition at line 2024 of file client.php.