phpCAS: CAS Basic client features (CAS 1.0, Service Tickets)
CAS Basic client features (CAS 1.0, Service Tickets)
[Implementation]
Functions
CASClient::getST ()
CASClient::setST ($st)
CASClient::hasST ()
CASClient::setCasServerCert ($cert)
CASClient::setCasServerCACert ($cert)
CASClient::setNoCasServerValidation ()
CASClient::validateST ($validate_url, &$text_response, &$tree_response)
Variables
CASClient::$_st
CASClient::$_cas_server_cert
CASClient::$_cas_server_ca_cert
CASClient::$_no_cas_server_validation
Function Documentation
CASClient::getST () [private, inherited]
This method returns the Service Ticket provided in the URL of the request.
Returns:
The service ticket.
Definition at line 1085 of file client.php.
Referenced by CASClient::isAuthenticated(), and CASClient::validateST().
CASClient::hasST () [private, inherited]
This method tells if a Service Ticket was stored.
Returns:
TRUE if a Service Ticket has been stored.
Definition at line 1101 of file client.php.
Referenced by CASClient::isAuthenticated().
CASClient::setCasServerCACert ($ cert) [inherited]
Set the CA certificate of the CAS server.
Parameters:
$cert the PEM certificate of the CA that emited the cert of the server
Definition at line 1153 of file client.php.
CASClient::setCasServerCert ($ cert) [inherited]
Set the certificate of the CAS server.
Parameters:
$cert the PEM certificate
Definition at line 1143 of file client.php.
CASClient::setNoCasServerValidation () [inherited]
Set no SSL validation for the CAS server.
Definition at line 1161 of file client.php.
CASClient::setST ($ st) [private, inherited]
This method stores the Service Ticket.
Parameters:
$st The Service Ticket.
Definition at line 1093 of file client.php.
Referenced by CASClient::wasPreviouslyAuthenticated().
CASClient::validateST ($ validate_url, &$ text_response, &$ tree_response) [private, inherited]
This method is used to validate a ST; halt on failure, and sets $validate_url, $text_reponse and $tree_response on success. These parameters are used later by CASClient::validatePGT() for CAS proxies.
Parameters:
$validate_url the URL of the request to the CAS server.
$text_response the response of the CAS server, as is (XML text).
$tree_response the response of the CAS server, as a DOM XML tree.
Returns:
bool TRUE when successfull, halt otherwise by calling CASClient::authError().
Definition at line 1179 of file client.php.
References CASClient::authError(), domxml_open_mem(), CASClient::getServerServiceValidateURL(), CASClient::getST(), CASClient::isProxy(), CASClient::readURL(), CASClient::setUser(), phpCAS::trace(), and phpCAS::traceBegin().
Variable Documentation
CASClient::$_cas_server_ca_cert [private, inherited]
the certificate of the CAS server CA.
Definition at line 1128 of file client.php.
CASClient::$_cas_server_cert [private, inherited]
the certificate of the CAS server.
Definition at line 1120 of file client.php.
CASClient::$_no_cas_server_validation [private, inherited]
Set to true not to validate the CAS server.
Definition at line 1136 of file client.php.
CASClient::$_st [private, inherited]
the Service Ticket provided in the URL of the request if present (empty otherwise). Written by CASClient::CASClient(), read by CASClient::getST() and CASClient::hasPGT().
Definition at line 1078 of file client.php.