phpCAS: Configuration
Configuration
[Implementation]
Modules
HTML output
Internationalization
Functions
CASClient::getServerVersion ()
CASClient::getServerHostname ()
CASClient::getServerPort ()
CASClient::getServerURI ()
CASClient::getServerBaseURL ()
CASClient::getServerLoginURL ($gateway=false, $renew=false)
CASClient::setServerLoginURL ($url)
CASClient::getServerServiceValidateURL ()
CASClient::getServerProxyValidateURL ()
CASClient::getServerProxyURL ()
CASClient::getServerLogoutURL ()
CASClient::setServerLogoutURL ($url)
CASClient::setExtraCurlOption ($key, $value)
CASClient::isHttps ()
CASClient::CASClient ($server_version, $proxy, $server_hostname, $server_port, $server_uri, $start_session=true)
Variables
CASClient::$_server
CASClient::$_curl_options = array()
Function Documentation
CASClient::CASClient ($ server_version, $ proxy, $ server_hostname, $ server_port, $ server_uri, $ start_session = true) [inherited]
CASClient constructor.
Parameters:
$server_version the version of the CAS server
$proxy TRUE if the CAS client is a CAS proxy, FALSE otherwise
$server_hostname the hostname of the CAS server
$server_port the port the CAS server is running on
$server_uri the URI the CAS server is responding on
$start_session Have phpCAS start PHP sessions (default true)
Returns:
a newly created CASClient object
Definition at line 490 of file client.php.
References phpCAS::error(), CASClient::getServerVersion(), CASClient::getURL(), CASClient::isCallbackMode(), CASClient::isHttps(), CASClient::isLogoutRequest(), CASClient::isProxy(), CASClient::setCallbackMode(), phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceEnd().
CASClient::getServerBaseURL () [private, inherited]
This method is used to retrieve the base URL of the CAS server.
Returns:
a URL.
Definition at line 302 of file client.php.
Referenced by CASClient::getServerLoginURL(), CASClient::getServerLogoutURL(), CASClient::getServerProxyURL(), CASClient::getServerProxyValidateURL(), CASClient::getServerServiceValidateURL(), and CASClient::HTMLFilterOutput().
CASClient::getServerHostname () [private, inherited]
This method is used to retrieve the hostname of the CAS server.
Returns:
the hostname of the CAS server.
Definition at line 278 of file client.php.
Referenced by CASClient::handleLogoutRequests().
CASClient::getServerLoginURL ($ gateway = false, $ renew = false) [private, inherited]
This method is used to retrieve the login URL of the CAS server.
Parameters:
$gateway true to check authentication, false to force it
$renew true to force the authentication with the CAS server NOTE : It is recommended that CAS implementations ignore the "gateway" parameter if "renew" is set
Returns:
a URL.
Definition at line 324 of file client.php.
References CASClient::getServerBaseURL(), CASClient::getURL(), phpCAS::traceBegin(), and phpCAS::traceEnd().
Referenced by CASClient::redirectToCas().
CASClient::getServerLogoutURL () [private, inherited]
This method is used to retrieve the logout URL of the CAS server.
Returns:
a URL.
Definition at line 425 of file client.php.
References CASClient::getServerBaseURL().
Referenced by CASClient::logout().
CASClient::getServerPort () [private, inherited]
This method is used to retrieve the port of the CAS server.
Returns:
the port of the CAS server.
Definition at line 286 of file client.php.
CASClient::getServerProxyURL () [private, inherited]
This method is used to retrieve the proxy URL of the CAS server.
Returns:
a URL.
Definition at line 404 of file client.php.
References CASClient::getServerBaseURL(), and CASClient::getServerVersion().
CASClient::getServerProxyValidateURL () [private, inherited]
This method is used to retrieve the proxy validating URL of the CAS server.
Returns:
a URL.
Definition at line 382 of file client.php.
References CASClient::getServerBaseURL(), CASClient::getServerVersion(), and CASClient::getURL().
CASClient::getServerServiceValidateURL () [private, inherited]
This method is used to retrieve the service validating URL of the CAS server.
Returns:
a URL.
Definition at line 360 of file client.php.
References CASClient::getServerBaseURL(), CASClient::getServerVersion(), and CASClient::getURL().
Referenced by CASClient::validateST().
CASClient::getServerURI () [private, inherited]
This method is used to retrieve the URI of the CAS server.
Returns:
a URI.
Definition at line 294 of file client.php.
CASClient::getServerVersion () [private, inherited]
This method is used to retrieve the version of the CAS server.
Returns:
the version of the CAS server.
Definition at line 268 of file client.php.
Referenced by CASClient::CASClient(), CASClient::getServerProxyURL(), CASClient::getServerProxyValidateURL(), CASClient::getServerServiceValidateURL(), and CASClient::HTMLFilterOutput().
CASClient::isHttps () [private, inherited]
This method checks to see if the request is secured via HTTPS
Returns:
true if https, false otherwise
Definition at line 463 of file client.php.
Referenced by CASClient::CASClient().
CASClient::setExtraCurlOption ($ key, $ value) [inherited]
This method is used to set additional user curl options.
Definition at line 453 of file client.php.
CASClient::setServerLoginURL ($ url) [private, inherited]
This method sets the login URL of the CAS server.
Parameters:
$url the login URL
Since:
0.4.21 by Wyman Chan
Definition at line 350 of file client.php.
CASClient::setServerLogoutURL ($ url) [private, inherited]
This method sets the logout URL of the CAS server.
Parameters:
$url the logout URL
Since:
0.4.21 by Wyman Chan
Definition at line 440 of file client.php.
Variable Documentation
CASClient::$_curl_options = array() [inherited]
An array to store extra curl options.
Definition at line 448 of file client.php.
CASClient::$_server [private, inherited]
a record to store information about the CAS server.
$_server["version"]: the version of the CAS server
$_server["hostname"]: the hostname of the CAS server
$_server["port"]: the port the CAS server is running on
$_server["uri"]: the base URI the CAS server is responding on
$_server["base_url"]: the base URL of the CAS server
$_server["login_url"]: the login URL of the CAS server
$_server["service_validate_url"]: the service validating URL of the CAS server
$_server["proxy_url"]: the proxy URL of the CAS server
$_server["proxy_validate_url"]: the proxy validating URL of the CAS server
$_server["logout_url"]: the logout URL of the CAS server
$_server["version"], $_server["hostname"], $_server["port"] and $_server["uri"] are written by CASClient::CASClient(), read by CASClient::getServerVersion(), CASClient::getServerHostname(), CASClient::getServerPort() and CASClient::getServerURI().
The other fields are written and read by CASClient::getServerBaseURL(), CASClient::getServerLoginURL(), CASClient::getServerServiceValidateURL(), CASClient::getServerProxyValidateURL() and CASClient::getServerLogoutURL().
Definition at line 256 of file client.php.