phpCAS: Miscellaneous
Miscellaneous
[Implementation]
Functions
CASClient::getURL ()
CASClient::setURL ($url)
CASClient::authError ($failure, $cas_url, $no_response, $bad_response='', $cas_response='', $err_code='', $err_msg='')
Variables
CASClient::$_url
$GLOBALS ['PHPCAS_CLIENT']
$GLOBALS ['PHPCAS_INIT_CALL']
$GLOBALS ['PHPCAS_AUTH_CHECK_CALL']
$GLOBALS ['PHPCAS_DEBUG']
Function Documentation
CASClient::authError ($ failure, $ cas_url, $ no_response, $ bad_response = '', $ cas_response = '', $ err_code = '', $ err_msg = '') [private, inherited]
This method is used to print the HTML output when the user was not authenticated.
Parameters:
$failure the failure that occured
$cas_url the URL the CAS server was asked for
$no_response the response from the CAS server (other parameters are ignored if TRUE)
$bad_response bad response from the CAS server ($err_code and $err_msg ignored if TRUE)
$cas_response the response of the CAS server
$err_code the error code given by the CAS server
$err_msg the error message given by the CAS server
Definition at line 2261 of file client.php.
References phpCAS::trace(), phpCAS::traceBegin(), and phpCAS::traceExit().
Referenced by CASClient::validateST().
CASClient::getURL () [private, inherited]
This method returns the URL of the current request (without any ticket CGI parameter).
Returns:
The URL
Definition at line 2183 of file client.php.
Referenced by CASClient::CASClient(), CASClient::getServerLoginURL(), CASClient::getServerProxyValidateURL(), and CASClient::getServerServiceValidateURL().
CASClient::setURL ($ url) [private, inherited]
This method sets the URL of the current request
Parameters:
$url url to set for service
Definition at line 2238 of file client.php.
Variable Documentation
CASClient::$_url [private, inherited]
the URL of the current request (without any ticket CGI parameter). Written and read by CASClient::getURL().
Definition at line 2173 of file client.php.
$GLOBALS['PHPCAS_DEBUG']
This global variable is used to store phpCAS debug mode.
Definition at line 225 of file CAS.php.
$GLOBALS['PHPCAS_AUTH_CHECK_CALL']
This global variable is used to store where the method checking the authentication is called from (to print comprehensive errors)
Definition at line 214 of file CAS.php.
$GLOBALS['PHPCAS_INIT_CALL']
This global variable is used to store where the initializer is called from (to print a comprehensive error in case of multiple calls).
Definition at line 203 of file CAS.php.
$GLOBALS['PHPCAS_CLIENT']
This global variable is used by the interface class phpCAS.
Definition at line 195 of file CAS.php.